### ISSUE TITLE
你的代码呢？

### ISSUE THREAD

**Issue by WZG3661** [yuancaimaiyi/colmap-fusion-gps#1]
怎么不开源你的代码？我记得colmap图像的gps，他的跟你这个有什么区别吗？

**Comment by yuancaimaiyi** [comment]
@WZG3661  不好意思，需要你自己动手实现，if 你看过vins 或者openmvg 或者opensfm代码，你就知道怎么写了，colmap 是可以read exif 信息，但是他gps没用来约束ba 。如果你稍微看过摄影测量这门课程，你就明白这叫gps 辅助空三！colmap 是一个开放的平台，需要你自己去add 各种传感器约束，加入自己的tricks！！！！！！！！！！！！！！！！！！！！
同时我开设的colmap  课程也会讲到gps 约束_

**Comment by chenziyu2016** [comment]
这个数据集哪里下载可否告知
