### ISSUE TITLE
这个数据集哪里下载可否告知

### ISSUE THREAD

**Issue by chenziyu2016** [yuancaimaiyi/colmap-fusion-gps#2]

**Comment by yuancaimaiyi** [comment]
kitti

**Comment by yuancaimaiyi** [comment]
@chenziyu2016 
常用数据集
1、ISPRS
https://www.isprs.org/education/benchmarks.aspx
2、sensefly
https://www.sensefly.com/education/datasets/
3、Kagaru
https://michaelwarren.info/docs/datasets/kagaru-airborne-stereo/
4、WHU
http://gpcv.whu.edu.cn/data/WHU_MVS_Stereo_dataset.html 
5、KITTI
http://www.cvlibs.net/datasets/kitti/
6、ETH
https://www.eth3d.net/ 
7、realitycapture
https://www.capturingreality.com/SampleDatasets 
8、视觉定位数据集
https://www.visuallocalization.net/datasets/
9、ODM
https://www.opendronemap.org/odm/datasets/
10、mve 官网的数据
https://www.gcc.tu-darmstadt.de/home/proj/ambient_point_clouds/apc.en.jsp
11、奥地利维也纳理工大学的Harvest4D项目(有GT）
https://harvest4d.org/?page_id=1367
12、自动化所偏古建筑
http://vision.ia.ac.cn/zh/data/index.html 
13、blendedmvs
https://github.com/YoYo000/BlendedMVS
14、Drone Mapping 
https://dronemapper.com/sample_data/
16、https://www.cs.cornell.edu/projects/bigsfm/#code bigsfm 
17、http://brian.harrison.org/Photogrammetry/JemezHistoricalSite/BodyJemez.html

**Comment by chenziyu2016** [comment]
太感谢了
