### ISSUE TITLE
does RTK is neccessary ?

### ISSUE THREAD

**Issue by cshang412** [yuancaimaiyi/colmap-fusion-gps#4]
Normally, the precise of gps is vary from 0-20m , is that neccessary to use rtk to make sure the gps is precise enough?  if not , which precise level of gps is needed?

**Comment by yuancaimaiyi** [comment]
@cshang412 
First of all, the accuracy of GPS is enough, but you need to check its smoothness.
Secondly, do you know what the core of GPS constraint is? As long as the relative position relationship is smooth and there is no problem, although the absolute accuracy of GPS is very poor, it doesn’t matter, as long as it is relatively ok, such as the data of the cheapest DJI mini flight, you can extract the GPS and you can clearly see that the data quality is still good, so it can be used for constraint
Finally, there is absolutely no problem with RTK for constraint, but bad points must be considered
(I talked about this issue in the live video three years ago)
